micronaut:
  application:
    name: test-course-template
  server:
    # port: 10001
    cors:
      enabled: true
  security:
    enabled: true
    authentication: cookie
    endpoints:
      login:
        enabled: true
        path: /users/signin
      logout:
        enabled: true
        path: /users/signout
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: supaDupaSecretThatNobodyWillKnow
        generator:
          access-token:
            expiration: 120
