micronaut:
  application:
    name: test-course-template
  server:
    port: 8080
    cors:
      enabled: true
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: supaDupaSecretThatNobodyWillKnow
        generator:
          access-token:
            expiration: 1500
